Algoritmo "Variáveis"
// Disciplina  :  Algoritmos e Lógica I
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Descrever variáveis
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/04/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro, nota2: real, nome: caractere, passou: logico
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo